
----------------------------------------------------------------------------------------------------
--                                                example
----------------------------------------------------------------------------------------------------
-- Descr: VHDL generated by InstantSOC 1.1.0 by FPGA-cores.com
-- Date:  14-06-2020 22:24:08
-- Src:   c:\Users\tbh\Desktop\instantSoC_test\example.cpp
----------------------------------------------------------------------------------------------------

----------------
-- LICENSE
----------------
-- Copyright (C) 2019 FPGA-Cores.com. 
-- This code is only free to use for non-commercial use and for evaluation purpose.
-- Commercial use needs a commercial license - contact FPGA-Cores.com.
-- The code is generated on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

-- -------------
-- DISCLAIMER
-- -------------
-- THIS CODE GENERATED BY TOOLS FROM FPGA-Cores.com IS PROVIDED "AS IS" AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
-- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL FPGA-Cores.com OR ANY 
-- OF THEIR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
-- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
-- WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS CODE, EVEN IF 
-- ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
-- Without limiting the foregoing, FPGA-Cores.com make no warranty that:
--    * the code will meet your requirements.
--    * the code will be uninterrupted, timely, secure or error-free.
--    * the results that may be obtained from the use of the code will be effective, accurate or reliable.
--    * the quality of the code will meet your expectations.
--    * any errors in the tools will be corrected.
--
-- The generated code and its documentation:
--    * could include technical or other mistakes, inaccuracies or typographical errors. 
--    * may be out of date and FPGA-Cores.com, its contributors, and FPGA Cores make no commitment to update such materials.
--
-- The use of the generated code is done at your own discretion and risk and with agreement 
-- that you will be solely responsible for any damage to your system or loss of data that results from such activities. 
-- No advice or information, whether oral or written, obtained by you from FPGA-Cores.com, its website, shall create any warranty for the code.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity example_TB is
end entity;

architecture SIM of example_TB is

    component example is
    port(
        clk : in std_logic;
        Gpio0 : out std_logic;
        Gpio1 : out std_logic;
        Gpio2 : out std_logic;
        Gpio3 : out std_logic;
        Gpio4 : out std_logic;
        Gpio5 : out std_logic;
        Gpio6 : out std_logic;
        Gpio7 : out std_logic
    );
    end component;

    signal clk : std_logic := '0';
    signal Gpio0 : std_logic := '0';
    signal Gpio1 : std_logic := '0';
    signal Gpio2 : std_logic := '0';
    signal Gpio3 : std_logic := '0';
    signal Gpio4 : std_logic := '0';
    signal Gpio5 : std_logic := '0';
    signal Gpio6 : std_logic := '0';
    signal Gpio7 : std_logic := '0';

begin

    --- The Device Under Test ---
    DUT : example
    port map(
        clk => clk,
        Gpio0 => Gpio0,
        Gpio1 => Gpio1,
        Gpio2 => Gpio2,
        Gpio3 => Gpio3,
        Gpio4 => Gpio4,
        Gpio5 => Gpio5,
        Gpio6 => Gpio6,
        Gpio7 => Gpio7
    );

    -- Clock Generation 10 MHz
    clk <= not clk after 50 ns;










end architecture;
